[package]
name = "mcmpi"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
rand = "0.9.2"
regex = "1.12.2"
reqwest = { version = "0.12.24", features = [ "blocking" ] }
zip = "6.0.0"
